version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio-sync
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5433/portfolio-sync"
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  pgdata: